version: "3.7"
services:
    mysql:
        container_name: "${DOCKER_CONTAINER_PREFIX}-mysql"
        image: mysql:8.0.18
        volumes:
        - /var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
        ports:
        - "${DOCKER_MYSQL_LOCAL_PORT}:3306"
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

    mysql-test:
        container_name: "${DOCKER_CONTAINER_PREFIX}-mysql-test"
        image: mysql:8.0.18
        environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=apptest
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']

    nginx:
        container_name: "${DOCKER_CONTAINER_PREFIX}-nginx"
        image: nginx:1.17.7-alpine
        working_dir: /app
        volumes:
        - .:/app:delegated
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
        - "${DOCKER_NGINX_LOCAL_PORT}:80"
        depends_on:
          - php-fpm

    php-fpm:
        container_name: "${DOCKER_CONTAINER_PREFIX}-php-fpm"
        build: docker/php-fpm
        working_dir: /app
        volumes:
        - .:/app:delegated
        depends_on:
          - mysql
        environment:
            PHP_IDE_CONFIG: "serverName=${DOCKER_SERVER_NAME}"

networks:
  default:
    name: "${DOCKER_CONTAINER_PREFIX}-default"
